version: "3"
services:
  client:
    image: "melikdaye/deep_somnia_client"
    hostname: client
  server:
    image: "melikdaye/deep-somnia-server"
    hostname: api
  nginx:
    image: "melikdaye/deep-somnia-nginx"
    hostname: nginx
    ports:
      - "80:80"