version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./node_server
    volumes:
      - /node_server/node_modules
      - ./node_server:/node_server
  client:
      stdin_open: true
      depends_on:
        - server
      build:
        dockerfile: Dockerfile
        context: ./deep_somnia_react
      volumes:
        - /app/node_modules
        - ./deep_somnia_react:/app
      ports:
        - "3000:3000"