version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile-dev
      context: ./
    volumes:
      - ./node_server/node_modules
      - ./:./node_server
    environment:
      - DB_URI=${DB_URI}
    ports:
      - "5000:5000"